# Generated by Django 2.0.5 on 2018-05-18 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sheet_week_from', models.DateField(blank=True, null=True)),
                ('time_sheet_week_to', models.DateField(blank=True, null=True)),
                ('total_week_hours', models.TimeField(blank=True, null=True)),
                ('date_mon', models.DateField(blank=True, null=True)),
                ('time_in_mon', models.TimeField(blank=True, null=True)),
                ('time_out_mon', models.TimeField(blank=True, null=True)),
                ('lunch_mon', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_mon', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_mon', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_mon', models.CharField(blank=True, max_length=250, null=True)),
                ('C', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_tue', models.DateField(blank=True, null=True)),
                ('time_in_tue', models.TimeField(blank=True, null=True)),
                ('time_out_tue', models.TimeField(blank=True, null=True)),
                ('lunch_tue', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_tue', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_tue', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_tue', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_tue', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_wed', models.DateField(blank=True, null=True)),
                ('time_in_wed', models.TimeField(blank=True, null=True)),
                ('time_out_wed', models.TimeField(blank=True, null=True)),
                ('lunch_wed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_wed', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_wed', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_wed', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_wed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_thu', models.DateField(blank=True, null=True)),
                ('time_in_thu', models.TimeField(blank=True, null=True)),
                ('time_out_thu', models.TimeField(blank=True, null=True)),
                ('lunch_thu', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_thu', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_thu', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_thu', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_thu', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_fri', models.DateField(blank=True, null=True)),
                ('time_in_fri', models.TimeField(blank=True, null=True)),
                ('time_out_fri', models.TimeField(blank=True, null=True)),
                ('lunch_fri', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_fri', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_fri', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_fri', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_fri', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_sat', models.DateField(blank=True, null=True)),
                ('time_in_sat', models.TimeField(blank=True, null=True)),
                ('time_out_sat', models.TimeField(blank=True, null=True)),
                ('lunch_sat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('vehicles_sat', models.CharField(blank=True, max_length=250, null=True)),
                ('job_address_sat', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description_sat', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_sat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
