# Generated by Django 2.0.5 on 2018-05-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeform',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeform', to=settings.AUTH_USER_MODEL),
        ),
    ]
